name: Docker Publish Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  docker_publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test
        run: mvn -B clean verify
      
      - name: Set up Docker Buildx
        if: ${{ success() }}
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ success() }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ success() }} # Add this line
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jjuless/sevyhuserservice:latest
